#include <stddef.h>
#include <stdio.h>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

int main(int argc, char **argv) {
 int w, h, c, i;
 unsigned char *pixels;
 FILE *f;
 
 if (argc != 4) {
  fprintf(stderr, "usage: %s <image path> <output path> <name>\n", argv[0]);
  return EXIT_FAILURE;
 }
 
 pixels = stbi_load(argv[1], &w, &h, &c, 4);
 if (pixels == NULL) {
  fprintf(stderr, "could not read image '%s'\n", argv[1]);
  return EXIT_FAILURE;
 }
 
 f = fopen(argv[2], "w");
 if (f == NULL) {
  fprintf(stderr, "could open output file '%s'\n", argv[2]);
  return EXIT_FAILURE;
 }
 
 fprintf(f, "// generated by https://github.com/tomthornt0n/image_to_c\n\nstruct\n{\nunsigned char pixels[%d];\nint width, height;\n} %s =\n{\n.pixels =\n{\n", w * h * 4, argv[3]);
 for (i = 0; i < w * h * 4; i += 4) {
  fprintf(f, "0x%x, 0x%x, 0x%x, 0x%x,\n", pixels[i + 0], pixels[i + 1], pixels[i + 2], pixels[i + 3]);
 }
 fprintf(f, "},\n.width = %d,\n.height = %d,\n};\n\n", w, h);
 
 fclose(f);
}
